---
# tasks file for nodejs

- name: Installing node and npm
  yum:
    name: ['nodejs', 'npm']
    enablerepo: epel
    state: installed
# ansible 2.1
#- name: Installing node and npm
#  yum:
#    name: "{{ item }}"
#    enablerepo: epel
#    state: installed
#  with_items:
#    - nodejs
#    - npm
